Repository rotisserie/eris, pull requests merged in 2020-01, with the labels that each got.

#47 doc: fix logrus link
  README.md
Labels: documentation

#46 feat: improve error wrapping, stack trace management, and formatting
  eris.go
  eris_test.go
  examples_test.go
  format.go
  format_test.go
  stack.go
Labels: enhancement

#59 fix: copy global root errors to ensure stack traces are isolated
  eris.go
Labels: bug

#56 docs: improve readme and godocs
  README.md
  doc.go
  example_format_test.go
  example_logger_test.go
  go.mod
  go.sum
Labels: documentation

#61 docs: remove example/dependencies and clean up readme
  README.md
  example_format_test.go
  example_logger_test.go
  go.mod
  go.sum
Labels: documentation

#65 fix: add discord invite link
  README.md
Labels: bug

#60 feat: eris errors are now compatible with sentry error tracing
  README.md
  eris.go
  eris_test.go
  stack.go
Labels: enhancement

#66 docs: add go playground links to examples
  examples_test.go
Labels: documentation

#71 refactor: check for global stack traces instead of forcing NewGlobal
  README.md
  eris.go
  eris_test.go
  examples_test.go
  stack.go
Labels: refactor
